# docker-compose.yml
version: "3.8"

services:
  db:
    image: mongo
    container_name: db
    volumes: 
      - mongodata:/data/db
    ports:
      - 27017:27017

  db-seed:
    container_name: db-seed
    env_file:
      - .env
    build:
      context: ./db-seed
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - db
      
  backend:
    container_name: backend
    build: ./multiflag-back
    volumes:
      - ./multiflag-back:/multiflag-back
      - /node_modules
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./multiflag-front
    volumes:
      - ./multiflag-front:/multiflag-front
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
volumes:
  mongodata: